// Generate a unique ID
const generateId = () => Math.random().toString(36).substring(2, 9)

// Mock course data
export const mockCourseData = [
  // Degree Courses
  {
    id: generateId(),
    name: "Bachelor of Medicine and Surgery",
    code: "MED-001",
    institution: "University of Nairobi",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 46.234,
    cluster: 13,
    duration: "6 Years",
    studyMode: "Full Time",
    description:
      "A comprehensive medical program that prepares students to become qualified medical doctors with skills in diagnosis, treatment, and prevention of diseases.",
    institutionDescription:
      "The University of Nairobi is Kenya's premier institution of higher learning with a strong focus on research and innovation.",
  },
  {
    id: generateId(),
    name: "Bachelor of Engineering (Electrical)",
    code: "ENG-102",
    institution: "Jomo Kenyatta University",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 43.756,
    cluster: 5,
    duration: "5 Years",
    studyMode: "Full Time",
    description:
      "This program focuses on electrical engineering principles, power systems, electronics, and telecommunications.",
    institutionDescription:
      "JKUAT is a leading technical university known for its strong engineering and technology programs.",
  },
  {
    id: generateId(),
    name: "Bachelor of Science (Computer Science)",
    code: "CS-201",
    institution: "Kenyatta University",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 41.234,
    cluster: 7,
    duration: "4 Years",
    studyMode: "Full Time",
    description:
      "A program that covers programming, algorithms, data structures, artificial intelligence, and software engineering.",
    institutionDescription:
      "Kenyatta University offers diverse academic programs with a focus on innovation and research.",
  },
  {
    id: generateId(),
    name: "Bachelor of Commerce",
    code: "COM-301",
    institution: "Strathmore University",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 39.567,
    cluster: 2,
    duration: "4 Years",
    studyMode: "Full Time",
    description: "A business program covering accounting, finance, marketing, and management principles.",
    institutionDescription:
      "Strathmore University is known for its excellence in business education and professional development.",
  },
  {
    id: generateId(),
    name: "Bachelor of Laws (LLB)",
    code: "LAW-101",
    institution: "University of Nairobi",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 44.89,
    cluster: 1,
    duration: "4 Years",
    studyMode: "Full Time",
    description:
      "A comprehensive legal education program that prepares students for careers in law practice, judiciary, and legal consultancy.",
    institutionDescription:
      "The University of Nairobi's School of Law is one of the oldest and most prestigious law schools in East Africa.",
  },
  {
    id: generateId(),
    name: "Bachelor of Science (Nursing)",
    code: "NUR-201",
    institution: "Moi University",
    institutionType: "university",
    location: "eldoret",
    category: "degree",
    cutoff: 38.456,
    cluster: 13,
    duration: "4 Years",
    studyMode: "Full Time",
    description:
      "A program that trains professional nurses with skills in patient care, health promotion, and disease prevention.",
    institutionDescription:
      "Moi University is a leading institution in western Kenya known for its strong health sciences programs.",
  },
  {
    id: generateId(),
    name: "Bachelor of Architecture",
    code: "ARCH-101",
    institution: "Technical University of Kenya",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 42.123,
    cluster: 6,
    duration: "5 Years",
    studyMode: "Full Time",
    description: "A program that focuses on architectural design, building technology, and urban planning.",
    institutionDescription:
      "The Technical University of Kenya offers practical, industry-focused education in technical fields.",
  },
  {
    id: generateId(),
    name: "Bachelor of Education (Science)",
    code: "EDU-301",
    institution: "Kenyatta University",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 35.678,
    cluster: 19,
    duration: "4 Years",
    studyMode: "Full Time",
    description: "A program that prepares students to become qualified science teachers at secondary school level.",
    institutionDescription: "Kenyatta University has a strong tradition in teacher education and educational research.",
  },
  {
    id: generateId(),
    name: "Bachelor of Science (Actuarial Science)",
    code: "ACT-201",
    institution: "University of Nairobi",
    institutionType: "university",
    location: "nairobi",
    category: "degree",
    cutoff: 43.234,
    cluster: 10,
    duration: "4 Years",
    studyMode: "Full Time",
    description:
      "A program that applies mathematical and statistical methods to assess risk in insurance, finance, and other industries.",
    institutionDescription:
      "The University of Nairobi offers one of the most competitive actuarial science programs in East Africa.",
  },
  {
    id: generateId(),
    name: "Bachelor of Science (Agriculture)",
    code: "AGR-101",
    institution: "Egerton University",
    institutionType: "university",
    location: "nakuru",
    category: "degree",
    cutoff: 34.567,
    cluster: 8,
    duration: "4 Years",
    studyMode: "Full Time",
    description:
      "A program focusing on crop production, animal husbandry, agricultural economics, and sustainable farming practices.",
    institutionDescription:
      "Egerton University is Kenya's premier agricultural university with extensive research facilities.",
  },

  // Diploma Courses
  {
    id: generateId(),
    name: "Diploma in Clinical Medicine",
    code: "DCM-101",
    institution: "Kenya Medical Training College",
    institutionType: "college",
    location: "nairobi",
    category: "diploma",
    cutoff: 32.456,
    cluster: 13,
    duration: "3 Years",
    studyMode: "Full Time",
    description:
      "A program that trains clinical officers to provide diagnostic, therapeutic, and preventive health services.",
    institutionDescription:
      "KMTC is the leading middle-level health training institution in Kenya with multiple campuses.",
  },
  {
    id: generateId(),
    name: "Diploma in Electrical Engineering",
    code: "DEE-201",
    institution: "Technical University of Mombasa",
    institutionType: "tvet",
    location: "mombasa",
    category: "diploma",
    cutoff: 30.789,
    cluster: 5,
    duration: "3 Years",
    studyMode: "Full Time",
    description: "A program that covers electrical installation, power systems, electronics, and electrical machines.",
    institutionDescription:
      "The Technical University of Mombasa offers practical technical education with a focus on coastal region needs.",
  },
  {
    id: generateId(),
    name: "Diploma in Information Technology",
    code: "DIT-301",
    institution: "Nairobi Technical Training Institute",
    institutionType: "tvet",
    location: "nairobi",
    category: "diploma",
    cutoff: 29.345,
    cluster: 7,
    duration: "2 Years",
    studyMode: "Full Time",
    description: "A program that covers computer applications, programming, networking, and database management.",
    institutionDescription:
      "NTTI is a leading technical training institute in Nairobi offering industry-relevant IT education.",
  },
  {
    id: generateId(),
    name: "Diploma in Business Management",
    code: "DBM-401",
    institution: "Kenya Institute of Management",
    institutionType: "college",
    location: "nairobi",
    category: "diploma",
    cutoff: 28.567,
    cluster: 2,
    duration: "2 Years",
    studyMode: "Full Time",
    description: "A program that covers business operations, management principles, marketing, and entrepreneurship.",
    institutionDescription:
      "KIM is a premier management development institution offering practical business education.",
  },
  {
    id: generateId(),
    name: "Diploma in Journalism and Mass Communication",
    code: "DJM-501",
    institution: "Kenya Institute of Mass Communication",
    institutionType: "college",
    location: "nairobi",
    category: "diploma",
    cutoff: 27.89,
    cluster: 3,
    duration: "2 Years",
    studyMode: "Full Time",
    description:
      "A program that trains students in news reporting, media production, public relations, and communication theory.",
    institutionDescription:
      "KIMC is the leading media training institution in Kenya with state-of-the-art broadcast facilities.",
  },

  // Certificate Courses
  {
    id: generateId(),
    name: "Certificate in Medical Laboratory Technology",
    code: "CMLT-101",
    institution: "Kenya Medical Training College",
    institutionType: "college",
    location: "kisumu",
    category: "certificate",
    cutoff: 25.456,
    cluster: 13,
    duration: "2 Years",
    studyMode: "Full Time",
    description:
      "A program that trains laboratory technicians to perform medical tests for diagnosis and treatment of diseases.",
    institutionDescription: "KMTC Kisumu offers quality health training with modern laboratory facilities.",
  },
  {
    id: generateId(),
    name: "Certificate in Automotive Engineering",
    code: "CAE-201",
    institution: "Rift Valley Technical Training Institute",
    institutionType: "tvet",
    location: "eldoret",
    category: "certificate",
    cutoff: 24.789,
    cluster: 5,
    duration: "2 Years",
    studyMode: "Full Time",
    description: "A program that covers vehicle mechanics, electrical systems, and automotive repair and maintenance.",
    institutionDescription:
      "RVTTI is a leading technical institution in the Rift Valley region with modern automotive workshops.",
  },
  {
    id: generateId(),
    name: "Certificate in Food and Beverage Production",
    code: "CFB-301",
    institution: "Kenya Utalii College",
    institutionType: "college",
    location: "nairobi",
    category: "certificate",
    cutoff: 23.345,
    cluster: 2,
    duration: "1 Year",
    studyMode: "Full Time",
    description: "A program that trains students in culinary arts, food preparation, and kitchen management.",
    institutionDescription: "Kenya Utalii College is the premier hospitality training institution in East Africa.",
  },

  // KMTC Courses
  {
    id: generateId(),
    name: "Diploma in Nursing",
    code: "DN-101",
    institution: "KMTC Nairobi",
    institutionType: "kmtc",
    location: "nairobi",
    category: "kmtc",
    cutoff: 33.456,
    cluster: 13,
    duration: "3.5 Years",
    studyMode: "Full Time",
    description: "A comprehensive nursing program that prepares students for careers in various healthcare settings.",
    institutionDescription: "KMTC Nairobi is the flagship campus of the Kenya Medical Training College network.",
  },
  {
    id: generateId(),
    name: "Diploma in Pharmacy",
    code: "DP-201",
    institution: "KMTC Mombasa",
    institutionType: "kmtc",
    location: "mombasa",
    category: "kmtc",
    cutoff: 32.789,
    cluster: 13,
    duration: "3 Years",
    studyMode: "Full Time",
    description:
      "A program that trains pharmaceutical technologists in drug dispensing, compounding, and pharmacy management.",
    institutionDescription: "KMTC Mombasa serves the coastal region with quality healthcare training programs.",
  },
  {
    id: generateId(),
    name: "Diploma in Medical Laboratory Sciences",
    code: "DMLS-301",
    institution: "KMTC Kisumu",
    institutionType: "kmtc",
    location: "kisumu",
    category: "kmtc",
    cutoff: 31.345,
    cluster: 13,
    duration: "3 Years",
    studyMode: "Full Time",
    description:
      "A program that trains laboratory technologists to perform complex medical tests and laboratory procedures.",
    institutionDescription: "KMTC Kisumu is a key healthcare training institution serving western Kenya.",
  },

  // Artisan Courses
  {
    id: generateId(),
    name: "Artisan in Welding and Fabrication",
    code: "AWF-101",
    institution: "Mombasa Technical Training Institute",
    institutionType: "tvet",
    location: "mombasa",
    category: "artisan",
    cutoff: 20.456,
    cluster: 5,
    duration: "1 Year",
    studyMode: "Full Time",
    description: "A hands-on program that trains students in metal welding, cutting, and fabrication techniques.",
    institutionDescription:
      "MTTI offers practical technical training with a focus on skills for the industrial sector.",
  },
  {
    id: generateId(),
    name: "Artisan in Plumbing and Pipe Fitting",
    code: "APP-201",
    institution: "Kisumu National Polytechnic",
    institutionType: "tvet",
    location: "kisumu",
    category: "artisan",
    cutoff: 19.789,
    cluster: 5,
    duration: "1 Year",
    studyMode: "Full Time",
    description: "A program that covers installation and repair of water supply, drainage, and sanitation systems.",
    institutionDescription:
      "Kisumu National Polytechnic offers quality technical training for the western Kenya region.",
  },
  {
    id: generateId(),
    name: "Artisan in Electrical Installation",
    code: "AEI-301",
    institution: "Nairobi Technical Training Institute",
    institutionType: "tvet",
    location: "nairobi",
    category: "artisan",
    cutoff: 21.345,
    cluster: 5,
    duration: "1 Year",
    studyMode: "Full Time",
    description:
      "A program that trains students in electrical wiring, installation, and maintenance for residential and commercial buildings.",
    institutionDescription: "NTTI provides practical electrical training with modern workshop facilities.",
  },
]
